export class FirstNationProperty {

    COMMUNITY_LOCATION_ID;
    FIRST_NATION_BC_NAME;
    FIRST_NATION_FEDERAL_NAME;
    FIRST_NATION_FEDERAL_ID;
    URL_TO_BC_WEBSITE;
    URL_TO_FEDERAL_WEBSITE;
    URL_TO_FIRST_NATION_WEBSITE;
    MEMBER_ORGANIZATION_NAMES;
    LANGUAGE_GROUP;
    BC_REGIONAL_OFFICE;
    MAPSHEET_NUMBER;
    PREFERRED_NAME;
    ALTERNATIVE_NAME_1;
    ALTERNATIVE_NAME_2;
    ADDRESS_LINE1;
    ADDRESS_LINE2;
    OFFICE_CITY;
    OFFICE_PROVINCE;
    OFFICE_POSTAL_CODE;
    LOCATION_DESCRIPTION;
    SITE_NAME;
    SITE_NUMBER;
    COMMENTS;
    OBJECTID;
    SE_ANNO_CAD_DATA;

}
